name: Bug Report
description: Create a report to help us improve.
title: "[Bug] "
labels: 🐛 BUG
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please ensure that this issue hasn't been reported before.

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Reproduction"
      description: "Detailed steps to reproduce the bug behavior."
      placeholder: "Please provide a minimal reproduction or steps to reproduce."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: "Environment"
      description: "Provide your system information, launcher version, launcher settings (from `sjmcl.conf.json`), or development environment information (full `tauri info` output) to help us better resolve the issue."

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
