name: Feature Request
description: Suggest an idea for SJMCL.
title: "[Feature] "
labels: 📝 Feature Request
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to request a new feature! Before submitting, please ensure that this feature hasn't already been requested by someone else.

  - type: textarea
    id: problem
    attributes:
      label: "Problem"
      description: "Is your feature request related to a problem? Please describe."
      placeholder: "e.g. I'm always frustrated when [...]"

  - type: textarea
    id: solution
    attributes:
      label: "Solution"
      description: "A clear and concise description of what you want to happen."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives"
      description: "A clear and concise description of any alternative solutions or features you've considered."

  - type: textarea
    id: context
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."
