name: Update Minecraft Versions

on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight UTC
  workflow_dispatch:

jobs:
  update-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run version fetch script
        run: node scripts/game/fetch_version_list.js

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          if git diff --quiet src-tauri/assets/game/version.txt; then
            echo "No changes to commit."
          else
            git add src-tauri/assets/game/version.txt
            git commit -m "chore: auto update Minecraft version list"
            git push
          fi
